title: Object Segmentation in Point Clouds
description: Supplementary material for paper D. Bobkov, S. Chen, M. Kiechle, S. Hilsenbeck, E. Steinbach "Noise-resistant Unsupervised Object Segmentation in Multi-view Indoor Point Clouds", 2017. The paper is presented in 12th International Joint Conference on Computer Vision, Imaging and Computer Graphics Theory and Applications in Porto, Portugal in February 2017.
show_downloads: false
google_analytics:
theme: jekyll-theme-cayman
